# Generated by Django 4.2.26 on 2025-12-01 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="Nome")),
                (
                    "cpf",
                    models.CharField(max_length=14, unique=True, verbose_name="CPF"),
                ),
                (
                    "cnh",
                    models.CharField(max_length=20, unique=True, verbose_name="CNH"),
                ),
                ("validade_cnh", models.DateField(verbose_name="Validade da CNH")),
            ],
            options={
                "verbose_name": "Motorista",
                "verbose_name_plural": "Motoristas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placa",
                    models.CharField(max_length=10, unique=True, verbose_name="Placa"),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="Modelo")),
                (
                    "ano",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1900)],
                        verbose_name="Ano",
                    ),
                ),
                (
                    "renavam",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="RENAVAM"
                    ),
                ),
                (
                    "km_atual",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="KM Atual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veículo",
                "verbose_name_plural": "Veículos",
                "ordering": ["placa"],
            },
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "origem",
                    models.CharField(default="", max_length=200, verbose_name="Origem"),
                ),
                ("destino", models.CharField(max_length=200, verbose_name="Destino")),
                ("hora_saida", models.TimeField(verbose_name="Hora de Saída")),
                (
                    "distancia",
                    models.FloatField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Distância (km)",
                    ),
                ),
                (
                    "km_atual",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="KM no Momento",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.motorista",
                        verbose_name="Motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
                "ordering": ["-data", "-hora_saida"],
            },
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "hora_infracao",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora da Infração"
                    ),
                ),
                ("local", models.CharField(max_length=200, verbose_name="Local")),
                (
                    "tipo_infracao",
                    models.CharField(
                        choices=[
                            ("Excesso de Velocidade", "Excesso de Velocidade"),
                            ("Estacionamento Irregular", "Estacionamento Irregular"),
                            ("Avanço de Sinal", "Avanço de Sinal"),
                            ("Uso de Celular", "Uso de Celular"),
                            ("Falta de Cinto", "Falta de Cinto"),
                            ("Documentação Irregular", "Documentação Irregular"),
                            ("Outros", "Outros"),
                        ],
                        max_length=100,
                        verbose_name="Tipo de Infração",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.motorista",
                        verbose_name="Motorista",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
                (
                    "viagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.viagem",
                        verbose_name="Viagem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multa",
                "verbose_name_plural": "Multas",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "tipo_servico",
                    models.CharField(
                        choices=[
                            ("Troca de Óleo", "Troca de Óleo"),
                            ("Revisão", "Revisão"),
                            ("Troca de Pneus", "Troca de Pneus"),
                            ("Alinhamento", "Alinhamento"),
                            ("Balanceamento", "Balanceamento"),
                            ("Freios", "Freios"),
                            ("Suspensão", "Suspensão"),
                            ("Outros", "Outros"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Serviço",
                    ),
                ),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "km_realizado",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="KM Realizado",
                    ),
                ),
                (
                    "proximo_servico_km",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Próximo Serviço (KM)",
                    ),
                ),
                (
                    "proximo_servico_data",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próximo Serviço (Data)"
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Valor",
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.veiculo",
                        verbose_name="Veículo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
                "ordering": ["-data"],
            },
        ),
    ]
