# Generated by Django 4.2.26 on 2025-12-02 11:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Motorista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("cnh", models.CharField(max_length=20, unique=True)),
                ("validade_cnh", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Veiculo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placa", models.CharField(max_length=10, unique=True)),
                ("modelo", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("renavam", models.CharField(max_length=20, unique=True)),
                (
                    "km_atual",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Viagem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_saida", models.TimeField()),
                ("origem", models.CharField(max_length=200)),
                ("destino", models.CharField(max_length=200)),
                (
                    "distancia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.motorista"
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.veiculo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora_infracao", models.TimeField(blank=True, null=True)),
                ("local", models.CharField(max_length=200)),
                ("tipo_infracao", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "motorista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.motorista"
                    ),
                ),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.veiculo"
                    ),
                ),
                (
                    "viagem",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.viagem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Manutencao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("tipo_servico", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "km_realizado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "proximo_servico_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("proximo_servico_data", models.DateField(blank=True, null=True)),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "veiculo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.veiculo"
                    ),
                ),
            ],
        ),
    ]
