# Generated by Django 4.2.26 on 2025-12-02 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="manutencao",
            options={
                "ordering": ["-data"],
                "verbose_name": "Manutenção",
                "verbose_name_plural": "Manutenções",
            },
        ),
        migrations.AlterModelOptions(
            name="motorista",
            options={"verbose_name": "Motorista", "verbose_name_plural": "Motoristas"},
        ),
        migrations.AlterModelOptions(
            name="multa",
            options={
                "ordering": ["-data"],
                "verbose_name": "Multa",
                "verbose_name_plural": "Multas",
            },
        ),
        migrations.AlterModelOptions(
            name="veiculo",
            options={"verbose_name": "Veículo", "verbose_name_plural": "Veículos"},
        ),
        migrations.AlterModelOptions(
            name="viagem",
            options={
                "ordering": ["-data", "-hora_saida"],
                "verbose_name": "Viagem",
                "verbose_name_plural": "Viagens",
            },
        ),
        migrations.AlterField(
            model_name="manutencao",
            name="data",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="manutencao",
            name="proximo_servico_km",
            field=models.DecimalField(
                blank=True, db_index=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="manutencao",
            name="tipo_servico",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="motorista",
            name="cnh",
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="motorista",
            name="cpf",
            field=models.CharField(db_index=True, max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="motorista",
            name="validade_cnh",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multa",
            name="data",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="multa",
            name="tipo_infracao",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="ano",
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="km_atual",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="veiculo",
            name="placa",
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="viagem",
            name="data",
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="manutencao",
            index=models.Index(fields=["-data"], name="core_manute_data_529ab8_idx"),
        ),
        migrations.AddIndex(
            model_name="manutencao",
            index=models.Index(
                fields=["veiculo", "data"], name="core_manute_veiculo_467caf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manutencao",
            index=models.Index(
                fields=["tipo_servico"], name="core_manute_tipo_se_26022a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="manutencao",
            index=models.Index(
                fields=["proximo_servico_km"], name="core_manute_proximo_50e881_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="motorista",
            index=models.Index(
                fields=["validade_cnh"], name="core_motori_validad_7e18a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="motorista",
            index=models.Index(
                fields=["-created_at"], name="core_motori_created_0e8e03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multa",
            index=models.Index(fields=["-data"], name="core_multa_data_08b651_idx"),
        ),
        migrations.AddIndex(
            model_name="multa",
            index=models.Index(
                fields=["motorista", "data"], name="core_multa_motoris_244e83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multa",
            index=models.Index(
                fields=["veiculo", "data"], name="core_multa_veiculo_eb76ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="multa",
            index=models.Index(
                fields=["tipo_infracao"], name="core_multa_tipo_in_ab9008_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veiculo",
            index=models.Index(
                fields=["km_atual"], name="core_veicul_km_atua_18319a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="veiculo",
            index=models.Index(fields=["ano"], name="core_veicul_ano_217ec7_idx"),
        ),
        migrations.AddIndex(
            model_name="veiculo",
            index=models.Index(
                fields=["-created_at"], name="core_veicul_created_b023cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viagem",
            index=models.Index(fields=["-data"], name="core_viagem_data_ebfca8_idx"),
        ),
        migrations.AddIndex(
            model_name="viagem",
            index=models.Index(
                fields=["motorista", "data"], name="core_viagem_motoris_c26a6e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="viagem",
            index=models.Index(
                fields=["veiculo", "data"], name="core_viagem_veiculo_23a973_idx"
            ),
        ),
    ]
