# Generated by Django 5.0.14 on 2025-12-18 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_manutencao_options_alter_motorista_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="viagem",
            name="km_final",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="KM Atual (Final)",
            ),
        ),
    ]
